In [1]:
import pandas as pd
import numpy as np

In [2]:
pd

In [3]:
df1 = pd.DataFrame([[4,5,6],[2,6,7],[7,8,9]], columns=['X', 'Y', 'Z'])

In [4]:
df1

   X  Y  Z
0  4  5  6
1  2  6  7
2  7  8  9

In [5]:
df2 = pd.DataFrame([[3,5,5],[1,6,6],[6,8,8]], columns=['P', 'Q', 'R'])

In [6]:
df2

   P  Q  R
0  3  5  5
1  1  6  6
2  6  8  8

In [7]:
df3 = pd.merge(df1, df2, right_on='Q', left_on='Y') #mapping of the corresponding columns

In [8]:
df3

   X  Y  Z  P  Q  R
0  4  5  6  3  5  5
1  2  6  7  1  6  6
2  7  8  9  6  8  8

In [9]:
left = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

In [10]:
right = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)

In [11]:
result = pd.merge(left, right, on="key")

In [12]:
result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [13]:
frames = [df1, df2]

In [14]:
df5 = pd.concat(frames) #to concatinate the dataframes

In [15]:
df5

     X    Y    Z    P    Q    R
0  4.0  5.0  6.0  NaN  NaN  NaN
1  2.0  6.0  7.0  NaN  NaN  NaN
2  7.0  8.0  9.0  NaN  NaN  NaN
0  NaN  NaN  NaN  3.0  5.0  5.0
1  NaN  NaN  NaN  1.0  6.0  6.0
2  NaN  NaN  NaN  6.0  8.0  8.0

In [16]:
df4 = df1.copy()

In [17]:
df4

   X  Y  Z
0  4  5  6
1  2  6  7
2  7  8  9

In [18]:
left.equals(right) #compare

False